Module timeout
RaspberryWallet/Backend pull request #9
Opened 2018-09-21 03:56 UTC by Furfel

Added timeout for `CheckRunnable` and fixed a bug where it could loop infinitely.

2018-09-21 03:57 UTC, Furfel commented on Manager/src/main/java/io/raspberrywallet/manager/modules/Module.java
> +import org.omg.CORBA.TIMEOUT;
Needs to be removed in the future (unused import, thanks jetbrains)

2018-09-21 10:37 UTC, stanbar requested changes
Please English comments, it looks bad

2018-09-26 17:35 UTC, stasbar commented
Are you going to change those comments? This PR is hanging for almost week 🤣

2018-09-27 08:54 UTC, PatrykMilewski commented
@Furfel

2018-09-28 13:03 UTC, pfoof commented
Lol, I changed the comments in some other push .-.

2018-09-28 13:28 UTC, PatrykMilewski commented
@Furfel there is still one, small conflict

2018-09-29 20:22 UTC, stanbar approved these changes
Good job, keep it up !

2018-09-29 20:23 UTC, merged